export interface EstimateSwapStep {
  type: SwapStepType;
  amountStartToken: number;
  estimate: number;
  startToken: string;
  endToken: string;
  provider: Provider;
}

export enum SwapStepType {
  DEPOSIT_TO_HIVE_ENGINE = "DEPOSIT_TO_HIVE_ENGINE",
  WITHDRAWAL_FROM_HIVE_ENGINE = "WITHDRAWAL_FROM_HIVE_ENGINE",
  SWAP_TOKEN = "SWAP_TOKEN",
  BUY_ON_HIVE_ENGINE_MARKET = "BUY_ON_HIVE_ENGINE_MARKET",
  SELL_ON_HIVE_ENGINE_MARKET = "SELL_ON_HIVE_ENGINE_MARKET",
  BUY_ON_MARKET = "BUY_ON_MARKET",
  SELL_ON_MARKET = "SELL_ON_MARKET",
}

export enum Provider {
  HIVE_INTERNAL_MARKET = "HIVE_INTERNAL_MARKET",
  BEESWAP = "BEESWAP",
  HIVE_PAY = "HIVE_PAY",
  DISCOUNTED_BRIDGE = "DISCOUNTED_BRIDGE",
  LEODEX = "LEODEX",
  HIVE_ENGINE = "HIVE_ENGINE",
  LIQUIDITY_POOL = "LIQUIDITY_POOL",
  HIVE_ENGINE_INTERNAL_MARKET = "HIVE_ENGINE_INTERNAL_MARKET",
  NULL = "NULL",
}

export enum SwapStatus {
  PENDING = "PENDING",
  STARTED = "STARTED",
  CANCELED_DUE_TO_ERROR = "CANCELED_DUE_TO_ERROR",
  REFUNDED_SLIPPAGE = "REFUND_SLIPPAGE",
  COMPLETED = "COMPLETED",
  FUNDS_RETURNED = "FUNDS_RETURNED",
}
